### ISSUE TITLE
One file for each type

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification-v2-default-schemas#1]
Instead of having a single yaml file with all the types, it seems a better idea to have separate files for each type (e.g. `default_variant_schema.yaml`).

**Comment by mbaudis** [comment]
+1 We could directly use a {S}[B] (like) JSON-Schema format/approach...

**Comment by mbaudis** [comment]
@sdelatorrep Picking this up again?

**Comment by sdelatorrep** [comment]
Done!

**Comment by mbaudis** [comment]
+1 - already a note :-)
