### ISSUE TITLE
rename default schemas

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#13]
The naming of the default schemas is overloaded. Instead of e.g. `default_variant_schema` it should just be e.g. `variant` and so forth; the scope of the schemas should be detailed separately, not in the name. One compromise option could be to specify `beacon_variant` but IMO it doesn't make much sense (version etc. have to be detailed anyway; "default" should be implicit).

**Comment by jrambla** [comment]
Solved in Beacon v2 Model.
