### ISSUE TITLE
Can't rely on Swagger Validator

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification-v2-default-schemas#25]
We have set up a mechanism to validate the YAML files using this tool from Swagger: https://github.com/swagger-api/validator-badge
For example, you can validate one file by calling: https://validator.swagger.io/validator/debug?url=https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/574321ffd1d7cd8e1d6b4d45c9f22ade7a1173b4/default_individual_schema.yaml
But this fails to validate references. 

In the file used in this call, there is a typo introduced on purpose to prove this:
```yaml
components:
  schemas:
    Treatment:
      description: blabla
      type: object
      properties:
        ageAtOnset:
          $ref: 'ccommon.yaml#/components/schemas/Age' # wrong file name
```
The validation is successful, although the referenced file does not exist.

If you open the file with Swagger UI (https://validator.swagger.io/), the error is **not** detected until you **expand** the object (`Treatment`) containing this reference.
![image](https://user-images.githubusercontent.com/17491353/109816536-2622f900-7c31-11eb-9a81-07888317384c.png)

In this very same [file](https://raw.githubusercontent.com/ga4gh-beacon/specification-v2-default-schemas/574321ffd1d7cd8e1d6b4d45c9f22ade7a1173b4/default_individual_schema.yaml), there is another reference to this external file (in `Disease`), but this time with the correct name, and it works perfectly fine:
```yaml
        ageOfOnset:
          $ref: 'common.yaml#/components/schemas/Age'
```
![image](https://user-images.githubusercontent.com/17491353/109817031-b5c8a780-7c31-11eb-8872-478387c806a6.png)

It seems it is a known issue of this Swagger validator (see [issue](https://github.com/swagger-api/validator-badge/issues/78)), but they haven't fixed it yet and does not seem to be a priority. 
For us, this means we can introduce errors in the files without noticing.

I haven't found any other tool to replace this one, but, if anybody knows one, please, share it with the team.

Finally, note that the online Swagger Editor (https://editor.swagger.io) **fails** to find external references if you use the relative path.

**Comment by jrambla** [comment]
We are shifting to a more comprehensive validation through the Beacon-verifier tool.
