### ISSUE TITLE
Use consistent id/label format for external references

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#29]
The current use of simple ids w/ CURIe syntax for external references (e.g. `PMID:20054560`), e.g.:

* <https://github.com/ga4gh-beacon/specification-v2-default-schemas/blob/afa5095823c513b54359f929d04c1a2b79cbe2ea/default_variant_interpretation_schema.yaml#L62>

It would be helpful to use at least objects in the standard `OntologyTerm` format (`id`, `label`) format, for readability & consistency.

**Comment by jrambla** [comment]
Corrected where spotted, please refer to specific places if any other found Beacon Framework v2 or Beacon v2 Models repos.
