### ISSUE TITLE
Id property names inconsistency

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2-default-schemas#31]
Hello,

There is an inconsistency in some ids properties:
pedigreeID, exposureID but,
phenotypeId, treatmentId, etc.

IMHO should be 'pedigreeId' and 'exposureId'.

Cheers,

Dmitry

**Comment by jrambla** [comment]
Corrected where spotted, please refer to specific places if any other found Beacon Framework v2 or Beacon v2 Models repos.
