### ISSUE TITLE
[Q] ClinicalRelevance & PhenotypicEffect objects

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2-default-schemas#36]
Hello,

There are two places these objects are defined:

https://github.com/ga4gh-beacon/specification-v2-default-schemas/blob/develop/default_variant_in_sample_schema.yaml
https://github.com/ga4gh-beacon/specification-v2-default-schemas/blob/develop/default_variant_interpretation_schema.yaml

Note that only required properties are IDs.
 
May these objects be unified?

Cheers,

D.

**Comment by jrambla** [comment]
We will explore these changes in draft4, as the Variant cluster of entry types needs revision
