### ISSUE TITLE
Proposal: Predefined handover types based on standard schemas

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#5]
The current _handover_ concept does not specify standardized data schemas to be used, but leaves this to the resource providers, so YMMV.

On the other hand, handover offers a tight security layer through the strict separation of Beacon response and data delivery, thereby allowing Beacons to operate w/o authentication, but to deliver data if run e.g. from within a secure enclave or after using any type of authentication mechanism not (necessarily the same used w/ the Beacon API).

Here, the proposal is to define all v2 data responses (e.g. like the _biosamples_ delivery from the `/g_variants/{id}/biosamples` path) with additional _handover_ types:

```
        {
          "description": "retrieve data of the biosamples matched by the query, in default Beacon biosample schema",
          "handoverType": {
            "id": "biosamples",
            "label": "Biosamples",
            "schema": "default"
          },
          "url": "http://progenetix.org/cgi-bin/beacondeliver.cgi?do=biosamplesdata&;amp;accessid=5beebe4c-e6e6-4dba-97b7-fc15ba6bf1db"
        }
```

**Comment by jrambla** [comment]
@mbaudis I would like to discuss this from a broader perspective and in the context of the other issues. Let me go back here later. So, not providing a more detailed answer yet.
