### ISSUE TITLE
Biosample does not contain attributes for histology and diagnostic codes

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#6]
The `Biosample` schema does not contain attributes for histology and diagnostic codes. The proper way to do this is demonstrated in [Phenopackets'](https://phenopackets-schema.readthedocs.io/en/latest/biosample.html) `histologicalDiagnosis`.
Alls, and this goes back to the work of the GA44GH Metadata Task Team,  there is a perceived need for a "bag of ontology terms" since, well, there isn't one to rule them all (for phenotypes, diseases):

* `phenotypic_features`
  - recommended
  - List of phenotypic abnormalities of the sample

**Comment by mbaudis** [comment]
... btw., why not directly using (& extending, if needed) the `Biosample` from phenopackets?

* <https://schemablocks.org/schemas/sb-phenopackets/current/Biosample.json> documentation in SchemaBlocks
* <https://schemablocks.org/schemas/sb-phenopackets/current/Biosample.json> JSON there
* <https://phenopackets-schema.readthedocs.io/en/latest/biosample.html> documentation at PXF

**Comment by mbaudis** [comment]
Looking at this again - this needs to be completely redone; and I come back to my earlier suggestion to basically start w/ Phenopackets and extend from there, where necessary. Or start from the [Progenetix Biosample](https://github.com/progenetix/schemas/blob/master/schemas/Biosample.yaml) schema (which is a child of the GA4GH developments).

**Comment by clauw87** [comment]
yes, Michael, we are doing exactly that, we have to update to include histological_diagnosis and other new fields.

**Comment by jrambla** [comment]
Hopefully, solved in Beacon v2 Model Draft4
